version: "3.6"

services:
  watchtower:
    container_name: watchtower
    restart: unless-stopped
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #This will update once a week at 4am on sunday 
    command: --schedule "0 0 4 * * SUN" --cleanup
    networks:
      - watchtower_lan

networks:
  watchtower_lan:
    driver: bridge    