version: "3.6"

services:
  ###
  #  Media Server
  #   - If you don't have a good graphics card for hardware acceleration I suggest trying to format movies in
  #     a .mp4 with H.264 8 bit video encoding and AAC audio, it is the most universally supported format
  #
  #  There are two jellyfin images used widely.  jellyfin/jellyfin and linuxserver/jellyfin
  #  I have decided to use linuxserver/jellyfin for the reason it is supposed to support
  #  hardware acceleration for Intel graphics where as jellyfin/jellyfin does not.  
  #
  #  I found that the commented sections can be useful if jellyfin is not dockerised, but a but overally complicated for me when running on
  #  a reverse proxy.
  ###
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional - Set the autodiscovery response domain or IP address.
    volumes:
      - ${GHS_DIR}/services/jellyfin/config:/config
      ### 
      # Media files for jellyfin are hosted on the filebrowser directories so that 
      # my family and friends can upload their own media easily.
      ###
      - ${GHS_DIR}/services/filebrowser/filebrowser_data/hosted_docs/jellyfin/tv_shows:/data/tvshows
      - ${GHS_DIR}/services/filebrowser/filebrowser_data/hosted_docs/jellyfin/movies:/data/movies
    ports:
      - 8096
      # - 8920:8920 #optional - Https webUI (you need to set up your own certificate).
      # - 7359:7359/udp #optional - Allows clients to discover Jellyfin on the local network.
      # - 1900:1900/udp #optional - Service discovery used by DNLA and clients.
    restart: unless-stopped
    networks:
      - jellyfin_lan

networks:
  jellyfin_lan:
    external: true   