version: "3.6"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: unless-stopped 
    volumes:
      - ${GHS_DIR}/services/adguardhome/home:/opt/adguardhome/work
      - ${GHS_DIR}/services/adguardhome/work:/opt/adguardhome/conf
    ports:
    # Ports mappings you may need:
      #plain DNS.
      - 53:53/tcp 
      - 53:53/udp
    
       # Add if you intend to use AdGuard Home as a DHCP server.
      # - 67:67/udp 
      # - 68:68/tcp
      # - 68:68/udp
    
       # Add if you are going to use AdGuard Home's admin panel as well as run
       # AdGuard Home as an HTTPS/DNS-over-HTTPS server.
      # - 80:80/tcp 
      # - 443:443/tcp 
      # - 443:443/udp 
      # - 3000:3000/tcp
    
       # Add if you are going to run AdGuard Home as a DNS-over-TLS server.
      - 853:853/tcp
    
       # Add if you are going to run AdGuard Home as a DNS-over-QUIC server. 
       # You may only leave one or two of these.
      - 784:784/udp 
      - 853:853/udp 
      - 8853:8853/udp
    
       # Add if you are going to run AdGuard Home as a DNSCrypt server.
      - 5443:5443/tcp 
      - 5443:5443/udp
    networks:
      - adguardhome_lan

networks:
  adguardhome_lan:
    external: true  